apiVersion: v1
kind: Pod
metadata:
  labels:
    app: minio
  name: minio
  namespace: default
spec:
  containers:
  - name: minio
    image: quay.io/minio/minio:latest
    command:
    - /bin/bash
    - -c
    args:
    - minio server /data --console-address :9090
---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: minio
  ports:
  - protocol: TCP
    port: 9000
    targetPort: 9000
