apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: housing-router-ab-test
  namespace: seldon
spec:
  annotations:
    seldon.io/headless-svc: "true"
  name: housing-router-ab-test
  predictors:
    - componentSpecs:
        - pdbSpec:
            maxUnavailable: 1
          spec:
            containers:
              - env:
                - name: MODEL_NAME
                  value: src.Preprocessor
                image: seldon-base:1.0.0
                imagePullPolicy: Never
                name: preprocessor
                resources:
                  requests:
                    memory: '100Mi'
                    cpu: '100m'
                  limits:
                    memory: '500Mi'
                    cpu: '500m'
              - env:
                - name: MODEL_NAME
                  value: src.Regressor
                image: seldon-base:1.0.0
                imagePullPolicy: Never
                name: model1
                resources:
                  requests:
                    memory: '100Mi'
                    cpu: '100m'
                  limits:
                    memory: '500Mi'
                    cpu: '500m'
              - env:
                - name: MODEL_NAME
                  value: src.Regressor
                image: seldon-base:1.0.0
                imagePullPolicy: Never
                name: model2
                resources:
                  requests:
                    memory: '100Mi'
                    cpu: '100m'
                  limits:
                    memory: '500Mi'
                    cpu: '500m'
              - env:
                - name: MODEL_NAME
                  value: src.Router
                image: seldon-base:1.0.0
                imagePullPolicy: Never
                name: router
                resources:
                  requests:
                    memory: '100Mi'
                    cpu: '100m'
                  limits:
                    memory: '500Mi'
                    cpu: '500m'
            terminationGracePeriodSeconds: 1
      graph:
        name: preprocessor
        type: MODEL
        children:
        - name: router
          type: ROUTER
          children:
          - name: model1
            type: MODEL
          - name: model2
            type: MODEL
          name: router
          parameters:
          - name: n_branches
            type: INT
            value: '2'
          - name: branch_names
            type: STRING
            value: model1:model2
          - name: branch_probabilities
            type: STRING
            value: 0.5:0.5
          - name: seed
            type: INT
            value: '1'
      name: router
      replicas: 1
      svcOrchSpec:
        env:
        - name: SELDON_ENABLE_ROUTING_INJECTION
          value: 'true'
      labels:
        version: v1
