apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: housing-regressor
  namespace: seldon
spec:
  annotations:
    seldon.io/headless-svc: "true"
  name: housing-regressor
  predictors:
    - componentSpecs:
        - spec:
            containers:
              - env:
                - name: MODEL_NAME
                  value: src.Regressor
                - name: TRACING
                  value: '1'
                - name: JAEGER_AGENT_HOST
                  value: jaeger-agent.jaeger.svc
                - name: JAEGER_AGENT_PORT
                  value: '5775'
                - name: JAEGER_SAMPLER_TYPE
                  value: const
                - name: JAEGER_SAMPLER_PARAM
                  value: '1'
                image: seldon-base:1.0.0
                imagePullPolicy: Never
                name: model
                resources:
                  requests:
                    memory: '100Mi'
                    cpu: '100m'
                  limits:
                    memory: '200Mi'
                    cpu: '200m'
            terminationGracePeriodSeconds: 1
      graph:
        children: []
        name: model
        type: MODEL
      name: model
      replicas: 1
      labels:
        version: v1
