apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-service
  namespace: default
  labels:
    app: model-service
spec:
  minReadySeconds: 5
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: model-service
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: model-service
    spec:
      containers:
      - name: model-service
        imagePullPolicy: Never
        image: model-service:latest
        ports:
        - containerPort: 5000
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /api/v1/readiness_check
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 60
          timeoutSeconds: 10
        livenessProbe:
          httpGet:
            path: /api/v1/healthcheck
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 10
        resources:
          requests:
            memory: "2000Mi"
            cpu: "1000m"
          limits:
            memory: "2000Mi"
            cpu: "4000m"
