name: Deploy KFP pipeline

on:
  push:
    branches:
      - main

jobs:
  kfp_apply:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        id: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"
          architecture: x64

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: actions/checkout@v2
      - name: Install packages
        run: |
          cd session6/kfp
          pip install -r requirements.txt
      - name: Build and deploy a new pipeline version
        env:
          KUBEFLOW_HOST: ${{ secrets.KUBEFLOW_HOST }}
          EXECUTOR_DOCKER_IMAGE_PULL_POLICY: Always
          PUSH_DOCKER_IMAGE: true
        run: |
          cd session6/kfp
          cp .env.example .env
          python pipeline.py
